[package]
name = "common"
version = "0.1.0"
edition = "2024"
description = "Shared data models and configuration for ForkForge API and CLI"

[dependencies]
serde = { workspace = true }
figment = { workspace = true }